# Generated by Django 3.0.6 on 2020-06-06 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('monthly_income', models.FloatField()),
                ('monthly_expenses', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_name', models.CharField(max_length=100, unique=True)),
                ('max_amount', models.FloatField()),
                ('current_amount', models.FloatField()),
                ('userAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgeter.UserAccount')),
            ],
        ),
    ]
