# Generated by Django 3.0.6 on 2020-05-31 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='current_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='budget',
            name='max_amount',
            field=models.FloatField(),
        ),
    ]
